def analysis_create():
    analysis = {}
    analysis['caseName'] = 'Smith Case'
    analysis['animationDelays'] = [1, 0.5]
    analysis['animationShadowShade'] = 0.2
    analysis['figureDelay'] = 0
    analysis['stackFigures'] = 'n'
    analysis['figuresCloseWhenDone'] = 'y'
    analysis['plotSurvivalProbabilities'] = 'n'
    analysis['plotScenarios'] = 'n'
    analysis['plotScenariosTypes'] = ['ri', 'rie', 'rif', 'rief']
    analysis['plotScenariosNumber'] = 10
    analysis['plotIncomeDistributions'] = 'n'
    analysis['plotIncomeDistributionsTypes'] = ['rc', 'ru', 'nc', 'nu']
    analysis['plotIncomeDistributionsStates'] = [[3], [1, 2]]
    analysis['plotIncomeDistributionsMinPctScenarios'] = 0.5
    analysis['plotIncomeDistributionsProportionShown'] = 1.00
    analysis['plotIncomeDistributionsPctMaxIncome'] = 100
    analysis['plotIncomeMaps'] = 'n'
    analysis['plotIncomeMapsTypes'] = ['ru', 'rc']
    analysis['plotIncomeMapsStates'] = [[3], [1, 2]]
    analysis['plotIncomeMapsMinPctScenarios'] = 0.5
    analysis['plotIncomeMapsPctMaxIncome'] = 100
    analysis['plotYOYIncomes'] = 'n'
    analysis['plotYOYIncomesTypes'] = ['r', 'n']
    analysis['plotYOYIncomesStates'] = [[3], [1, 2]]
    analysis['plotYOYIncomesWithZero'] = 'y'
    analysis['plotRecipientPVs'] = 'n'
    analysis['plotPPCSandIncomes'] = 'n'
    analysis['plotPPCSandIncomesSemilog'] = 'y'
    analysis['plotPPCSandIncomesStates'] = [[3]]
    analysis['plotPPCSandIncomesMinPctScenarios'] = 0.5
    analysis['plotYearlyPVs'] = 'n'
    analysis['plotYearlyPVsStates'] = [[3, 1, 2]]
    analysis['plotYearlyPVsMinPctScenarios'] = 0.5
    analysis['plotEfficientIncomes'] = 'n'
    analysis['plotEfficientIncomesStates'] = [[3], [1, 2]]
    analysis['plotEfficientIncomesTypes'] = ['pcl']
    analysis['plotEfficientIncomesMinPctScenarios'] = 0.5
    return analysis
